code --install-extension aaron-bond.better-comments
code --install-extension akamud.vscode-theme-onedark
code --install-extension anseki.vscode-color
code --install-extension bradlc.vscode-tailwindcss
code --install-extension chakrounanas.turbo-console-log
code --install-extension cweijan.dbclient-jdbc
code --install-extension cweijan.vscode-mysql-client2
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension golang.go
code --install-extension humao.rest-client
code --install-extension mhutchie.git-graph
code --install-extension mkloubert.vscode-kanban
code --install-extension ms-playwright.playwright
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.extension-test-runner
code --install-extension ms-vscode.js-debug-nightly
code --install-extension ms-vscode.remote-repositories
code --install-extension ms-vscode.vscode-selfhost-test-provider
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension naumovs.color-highlight
code --install-extension oderwat.indent-rainbow
code --install-extension quicktype.quicktype
code --install-extension rangav.vscode-thunder-client
code --install-extension svelte.svelte-vscode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wix.glean
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.javascriptsnippets